### ISSUE TITLE
NullPointerException for inputs into downstream steps

### ISSUE THREAD

**Issue by vardaofthevalier** [googlegenomics/dockerflow#11]
Here is the workflow that I'm attempting to run:

```
defn:
  name: bam-pipeline-example
  description: Run FastQC and Picard on a BAM file downloaded from the GDC
args:
  inputs:
    FILE_UUID: REQUIRED
    DISK_SIZE: REQUIRED
    GDC_DATA_DESTINATION: REQUIRED
    RESULTS_DESTINATION: REQUIRED
    GDC_TOKEN_URI: REQUIRED
    BAM_FILENAME: REQUIRED

    downloadBam.GDC_TOKEN: ${GDC_TOKEN_URI}

    fastqc.BAM: ${downloadBam.BAM}
    fastqc.BAI: ${downloadBam.BAI}

    picard.BAM: ${downloadBam.BAM}
    picard.BAI: ${downloadBam.BAI}

  outputs:
    downloadBam.BAM: ${GDC_DATA_DESTINATION}/${BAM_FILENAME}
    downloadBam.BAI: ${GDC_DATA_DESTINATION}/${BAM_FILENAME}.bai

    fastqc.ZIP: ${RESULTS_DESTINATION}
    fastqc.HTML: ${RESULTS_DESTINATION}

    picardBamindexstats.BAM_INDEX_STATS: ${RESULTS_DESTINATION}

graph:
- downloadBam
- BRANCH:
  - fastqc
  - picardBamindexstats

steps:
- defn:
    name: downloadBam
    description: Download a BAM file from the GDC given a file UUID and copy the resulting file to GCS
    inputParameters:
    - name: GDC_TOKEN
      localCopy:
        disk: gdc-data
        path: gdc-token.txt
    - name: FILE_UUID
      defaultValue: ${FILE_UUID}
    outputParameters:
    - name: BAM
      localCopy:
        disk: gdc-data
        path: ${FILE_UUID}/${BAM_FILENAME}
    - name: BAI
      localCopy:
        disk: gdc-data
        path: ${FILE_UUID}/${BAM_FILENAME}.bai
    resources:
      minimumCpuCores: 4
      minimumRamGb: 16
      preemptible: true
      zones:
      - us-central1-a
      - us-central1-b
      - us-central1-c
      - us-central1-f
      - us-east1-b
      - us-east1-c
      - us-east1-d
      - us-west1-a
      - us-west1-b
      disks:
        - name: gdc-data
          type: PERSISTENT_SSD
          sizeGb: ${DISK_SIZE}
          mountPoint: /gdc-data
    docker:
      imageName: b.gcr.io/isb-cgc-public-docker-images/gdc-client:1.0.1
      cmd: "cd /gdc-data && gdc-client download -t $GDC_TOKEN $FILE_UUID"
- defn:
    name: fastqc
    description: Run fastqc on a BAM file
    inputParameters:
    - name: BAM
      localCopy:
        disk: fastqc
        path: ${BAM_FILENAME}
    - name: BAI
      localCopy:
          disk: fastqc
          path: ${BAM_FILENAME}.bai
    outputParameters:
    - name: ZIP
      localCopy:
        disk: fastqc
        path: ${FILE_UUID}-${BAM_FILENAME}_fastqc.zip
    - name: HTML
      localCopy:
        disk: fastqc
        path: ${FILE_UUID}-${BAM_FILENAME}_fastqc.html
    resources:
      minimumCpuCores: 2
      minimumRamGb: 4
      preemptible: true
      zones:
      - us-central1-a
      - us-central1-b
      - us-central1-c
      - us-central1-f
      - us-east1-b
      - us-east1-c
      - us-east1-d
      - us-west1-a
      - us-west1-b
      disks:
        - name: fastqc
          type: PERSISTENT_SSD
          sizeGb: ${DISK_SIZE}
          mountPoint: /fastqc
    docker:
      imageName: b.gcr.io/isb-cgc-public-docker-images/qctools
      cmd: "cd /fastqc && fastqc $BAM && mv *.zip $ZIP && mv *.html $HTML"
- defn:
    name: picardBamindexstats
    description: Run BamIndexStats on a BAM file
    inputParameters:
    - name: BAM
      localCopy:
          disk: fastqc
          path: ${BAM_FILENAME}
    - name: BAI
      localCopy:
          disk: fastqc
          path: ${BAM_FILENAME}.bai
    outputParameters:
    - name: BAM_INDEX_STATS
      localCopy:
        disk: picard
        path: ${FILE_UUID}-${BAM_FILENAME}.bamIndexStats.tsv
    resources:
      minimumCpuCores: 2
      minimumRamGb: 4
      preemptible: true
      zones:
      - us-central1-a
      - us-central1-b
      - us-central1-c
      - us-central1-f
      - us-east1-b
      - us-east1-c
      - us-east1-d
      - us-west1-a
      - us-west1-b
      disks:
        - name: picard
          type: PERSISTENT_SSD
          sizeGb: ${DISK_SIZE}
          mountPoint: /picard
    docker:
      imageName: b.gcr.io/isb-cgc-public-docker-images/qctools
      cmd: "cd /picard && java -jar /usr/picard/picard.jar BamIndexStats VALIDATION_STRINGENCY=LENIENT INPUT=$BAM TMP_DIR=./tmp > $BAM_INDEX_STATS"
```

And here is the error that I get in the Dataflow UI after the first step is nearly complete:

```
(3e5e1547d46d5d5e): java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.NullPointerException: Null value for path BAM at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:162) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnContext.outputWindowedValue(DoFnRunnerBase.java:287) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnContext.outputWindowedValue(DoFnRunnerBase.java:283) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnProcessContext$1.outputWindowedValue(DoFnRunnerBase.java:507) at com.google.cloud.dataflow.sdk.util.GroupAlsoByWindowsAndCombineDoFn.closeWindow(GroupAlsoByWindowsAndCombineDoFn.java:205) at com.google.cloud.dataflow.sdk.util.GroupAlsoByWindowsAndCombineDoFn.processElement(GroupAlsoByWindowsAndCombineDoFn.java:192) at com.google.cloud.dataflow.sdk.util.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:49) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.processElement(DoFnRunnerBase.java:138) at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:190) at com.google.cloud.dataflow.sdk.runners.worker.ForwardingParDoFn.processElement(ForwardingParDoFn.java:42) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerLoggingParDoFn.processElement(DataflowWorkerLoggingParDoFn.java:47) at com.google.cloud.dataflow.sdk.util.common.worker.ParDoOperation.process(ParDoOperation.java:55) at com.google.cloud.dataflow.sdk.util.common.worker.OutputReceiver.process(OutputReceiver.java:52) at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:202) at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.start(ReadOperation.java:143) at com.google.cloud.dataflow.sdk.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:72) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.executeWork(DataflowWorker.java:287) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.doWork(DataflowWorker.java:223) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.getAndPerformWork(DataflowWorker.java:173) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.doWork(DataflowWorkerHarness.java:193) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:173) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:160) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.NullPointerException: Null value for path BAM at com.google.cloud.dataflow.sdk.util.UserCodeException.wrap(UserCodeException.java:35) at com.google.cloud.dataflow.sdk.util.UserCodeException.wrapIf(UserCodeException.java:40) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.wrapUserCodeException(DoFnRunnerBase.java:368) at com.google.cloud.dataflow.sdk.util.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:51) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.processElement(DoFnRunnerBase.java:138) at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:190) at com.google.cloud.dataflow.sdk.runners.worker.ForwardingParDoFn.processElement(ForwardingParDoFn.java:42) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerLoggingParDoFn.processElement(DataflowWorkerLoggingParDoFn.java:47) at com.google.cloud.dataflow.sdk.util.common.worker.ParDoOperation.process(ParDoOperation.java:55) at com.google.cloud.dataflow.sdk.util.common.worker.OutputReceiver.process(OutputReceiver.java:52) at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:160) ... 25 more Caused by: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.NullPointerException: Null value for path BAM at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:162) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnContext.outputWindowedValue(DoFnRunnerBase.java:287) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnProcessContext.output(DoFnRunnerBase.java:449) at com.google.cloud.dataflow.sdk.runners.worker.CombineValuesFnFactory$ExtractOutputDoFn.processElement(CombineValuesFnFactory.java:272) Caused by: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.NullPointerException: Null value for path BAM at com.google.cloud.dataflow.sdk.util.UserCodeException.wrap(UserCodeException.java:35) at com.google.cloud.dataflow.sdk.util.UserCodeException.wrapIf(UserCodeException.java:40) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.wrapUserCodeException(DoFnRunnerBase.java:368) at com.google.cloud.dataflow.sdk.util.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:51) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.processElement(DoFnRunnerBase.java:138) at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:190) at com.google.cloud.dataflow.sdk.runners.worker.ForwardingParDoFn.processElement(ForwardingParDoFn.java:42) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerLoggingParDoFn.processElement(DataflowWorkerLoggingParDoFn.java:47) at com.google.cloud.dataflow.sdk.util.common.worker.ParDoOperation.process(ParDoOperation.java:55) at com.google.cloud.dataflow.sdk.util.common.worker.OutputReceiver.process(OutputReceiver.java:52) at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:160) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnContext.outputWindowedValue(DoFnRunnerBase.java:287) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnProcessContext.output(DoFnRunnerBase.java:449) at com.google.cloud.dataflow.sdk.runners.worker.CombineValuesFnFactory$ExtractOutputDoFn.processElement(CombineValuesFnFactory.java:272) at com.google.cloud.dataflow.sdk.util.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:49) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.processElement(DoFnRunnerBase.java:138) at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:190) at com.google.cloud.dataflow.sdk.runners.worker.ForwardingParDoFn.processElement(ForwardingParDoFn.java:42) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerLoggingParDoFn.processElement(DataflowWorkerLoggingParDoFn.java:47) at com.google.cloud.dataflow.sdk.util.common.worker.ParDoOperation.process(ParDoOperation.java:55) at com.google.cloud.dataflow.sdk.util.common.worker.OutputReceiver.process(OutputReceiver.java:52) at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:160) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnContext.outputWindowedValue(DoFnRunnerBase.java:287) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnContext.outputWindowedValue(DoFnRunnerBase.java:283) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnProcessContext$1.outputWindowedValue(DoFnRunnerBase.java:507) at com.google.cloud.dataflow.sdk.util.GroupAlsoByWindowsAndCombineDoFn.closeWindow(GroupAlsoByWindowsAndCombineDoFn.java:205) at com.google.cloud.dataflow.sdk.util.GroupAlsoByWindowsAndCombineDoFn.processElement(GroupAlsoByWindowsAndCombineDoFn.java:192) at com.google.cloud.dataflow.sdk.util.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:49) at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.processElement(DoFnRunnerBase.java:138) at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:190) at com.google.cloud.dataflow.sdk.runners.worker.ForwardingParDoFn.processElement(ForwardingParDoFn.java:42) at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerLoggingParDoFn.processElement(DataflowWorkerLoggingParDoFn.java:47) at com.google.cloud.dataflow.sdk.util.common.worker.ParDoOperation.process(ParDoOperation.java:55) at com.google.cloud.dataflow.sdk.util.common.worker.OutputReceiver.process(OutputReceiver.java:52) at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:202) at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.start(ReadOperation.java:143) at com.google.cloud.dataflow.sdk.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:72) at com.google.
```

Oddly enough the first step is marked as failed in the Dataflow Graph, but the BAM file that I downloaded from the GDC in that step was uploaded to GCS successfully.  I can also verify that the GGP operation officially succeeded, so something weird is happening when attempting to chain output parameters of one step to input parameters of another.  

I'm not sure if there's anything obviously wrong with the workflow YAML itself, but I have tried to model it off of everything I've seen so far in the [YAML resources](https://github.com/googlegenomics/dockerflow/tree/master/src/test/resources) directory.
